imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: apc
#        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: root@assessment.nwp.org
            to_email:   awc-support@nwp.org
            subject:    Assessment - An Error Occurred!
            level:      debug
